### ISSUE TITLE
Compiling does not work with GCC 4.8.2

### ISSUE THREAD

**Issue by samfux84** [odelaneau/shapeit4#5]
Hi,

Today I tried to install shapeit4 on our universities HPC cluster. Using GCC 4.8.2, HTSLIB 1.7 and BOOST 1.63.0, compiling failed with an error message:

```
[sfux@eu-c7-050-15 shapeit4]$ make
g++ -std=c++0x -O3 -c src/containers/genotype_set.cpp -o obj/genotype_set.o -Isrc -I/cluster/apps/gdc/samtools/1.7/include -I/cluster/apps/gdc/boost/1.63.0/include
In file included from src/utils/otools.h:64:0,
                 from src/containers/genotype_set.h:25,
                 from src/containers/genotype_set.cpp:22:
src/utils/timer.h: In member function ‘std::string timer::date()’:
src/utils/timer.h:59:12: error: ‘put_time’ is not a member of ‘std’
      ss << std::put_time(std::localtime(&in_time_t), "%d/%m/%Y - %X");
            ^
make: *** [obj/genotype_set.o] Error 1
[sfux@eu-c7-050-15 shapeit4]
```

The documentation does not indicate, which GCC versions are supported and should work fine. Please add this to the documentation as it would make it much easier to install the software if the requirements are more clear.

And please also make a versioned release. This repository has 0 releases. If scientists use your software, and afterwards publish some results, they need to refer to the software they used. To avoid that people write sentences like, "the results were computed using shapeit4 commit 4ae17509c38c6659704d42bdfa23789e71e7eacd" it would be nice to have a release with a version number.

Best regards

Sam

**Comment by samfux84** [comment]
Nobody around ?

**Comment by odelaneau** [comment]
Hi,

The issue is related to gcc version. I usually compile it with version >= 6, but I think it also works fine with version 5. Better packaging, release and documentation will be done in September.

Best wishes,

Olivier.

**Comment by samfux84** [comment]
Thank you for your reply. I tried with GCC 5.2.0 and it worked.
